const FRUIT_EMOJI = {
  apple: '🍎',
  pear: '🍐',
  cherry: '🍒',
  'sour cherry': '🍒',
  plum: '🟣',
  peach: '🍑',
  apricot: '🍑',
  orange: '🍊',
  mandarin: '🍊',
  lemon: '🍋',
  lime: '🍋',
  fig: '🟤',
  grape: '🍇',
  mulberry: '🫐',
  blueberry: '🫐',
  blackberry: '🫐',
  raspberry: '🍓',
  strawberry: '🍓',
  walnut: '🌰',
  chestnut: '🌰',
  hazelnut: '🌰',
  almond: '🌰',
  olive: '🫒',
  banana: '🍌',
  mango: '🥭',
  avocado: '🥑',
  pomegranate: '🔴',
  quince: '🍈',
  melon: '🍈',
  kiwi: '🥝',
  coconut: '🥥',
  elderberry: '🌸',
  'rose hip': '🌹',
}

export function fruitEmoji(fruitType) {
  if (!fruitType) return '🌳'
  return FRUIT_EMOJI[fruitType.trim().toLowerCase()] ?? '🌳'
}

export const COMMON_FRUITS = [
  'Apple',
  'Pear',
  'Cherry',
  'Sour cherry',
  'Plum',
  'Peach',
  'Apricot',
  'Fig',
  'Grape',
  'Mulberry',
  'Walnut',
  'Chestnut',
  'Hazelnut',
  'Quince',
  'Pomegranate',
  'Orange',
  'Lemon',
  'Olive',
  'Elderberry',
  'Rose hip',
]
